/*
 * Generated by erpcgen 1.9.1 on Wed Aug 31 15:16:23 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_qspi_rad_test_h_)
#define _qspi_rad_test_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10901 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief QSPIService identifiers */
enum _QSPIService_ids
{
    kQSPIService_service_id = 1,
    kQSPIService_sectorErase_id = 1,
    kQSPIService_pageRead_id = 2,
    kQSPIService_pageWrite_id = 3,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name QSPIService
//@{
int32_t sectorErase(uint32_t addr);

int32_t pageRead(uint32_t addr, uint8_t data[256]);

int32_t pageWrite(uint32_t addr, const uint8_t data[256]);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _qspi_rad_test_h_
