#
# Generated by erpcgen 1.9.1 on Wed Aug 31 15:16:27 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for QSPIService
class IQSPIService(object):
    SERVICE_ID = 1
    SECTORERASE_ID = 1
    PAGEREAD_ID = 2
    PAGEWRITE_ID = 3

    def sectorErase(self, addr):
        raise NotImplementedError()

    def pageRead(self, addr, data):
        raise NotImplementedError()

    def pageWrite(self, addr, data):
        raise NotImplementedError()


