#
# Generated by erpcgen 1.9.1 on Tue Oct 18 17:30:21 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for QSPIService
class QSPIServiceService(erpc.server.Service):
    def __init__(self, handler):
        super(QSPIServiceService, self).__init__(interface.IQSPIService.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.IQSPIService.SECTORERASE_ID: self._handle_sectorErase,
                interface.IQSPIService.PAGEREAD_ID: self._handle_pageRead,
                interface.IQSPIService.PAGEWRITE_ID: self._handle_pageWrite,
                interface.IQSPIService.CHIPSELECT_ID: self._handle_chipSelect,
                interface.IQSPIService.CHIPINITIAL_ID: self._handle_chipInitial,
                interface.IQSPIService.READCURRENT_ID: self._handle_readCurrent,
            }

    def _handle_sectorErase(self, sequence, codec):
        # Read incoming parameters.
        addr = codec.read_uint32()

        # Invoke user implementation of remote function.
        _result = self._handler.sectorErase(addr)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IQSPIService.SERVICE_ID,
            request=interface.IQSPIService.SECTORERASE_ID,
            sequence=sequence))
        codec.write_int32(_result)

    def _handle_pageRead(self, sequence, codec):
        # Create reference objects to pass into handler for out/inout parameters.
        data = erpc.Reference()

        # Read incoming parameters.
        addr = codec.read_uint32()

        # Invoke user implementation of remote function.
        _result = self._handler.pageRead(addr, data)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IQSPIService.SERVICE_ID,
            request=interface.IQSPIService.PAGEREAD_ID,
            sequence=sequence))
        if data.value is None:
            raise ValueError("data.value is None")
        for _i0 in data.value:
            codec.write_uint8(_i0)

        codec.write_int32(_result)

    def _handle_pageWrite(self, sequence, codec):
        # Read incoming parameters.
        addr = codec.read_uint32()
        data = []
        for _i0 in range(256):
            _v0 = codec.read_uint8()
            data.append(_v0)


        # Invoke user implementation of remote function.
        _result = self._handler.pageWrite(addr, data)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IQSPIService.SERVICE_ID,
            request=interface.IQSPIService.PAGEWRITE_ID,
            sequence=sequence))
        codec.write_int32(_result)

    def _handle_chipSelect(self, sequence, codec):
        # Read incoming parameters.
        chip = codec.read_uint8()

        # Invoke user implementation of remote function.
        _result = self._handler.chipSelect(chip)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IQSPIService.SERVICE_ID,
            request=interface.IQSPIService.CHIPSELECT_ID,
            sequence=sequence))
        codec.write_int32(_result)

    def _handle_chipInitial(self, sequence, codec):
        # Create reference objects to pass into handler for out/inout parameters.
        initial_state = erpc.Reference()

        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.chipInitial(initial_state)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IQSPIService.SERVICE_ID,
            request=interface.IQSPIService.CHIPINITIAL_ID,
            sequence=sequence))
        if initial_state.value is None:
            raise ValueError("initial_state.value is None")
        codec.write_uint8(initial_state.value)
        codec.write_int32(_result)

    def _handle_readCurrent(self, sequence, codec):
        # Create reference objects to pass into handler for out/inout parameters.
        memory_value = erpc.Reference()

        # Read incoming parameters.
        slave_address = codec.read_uint8()
        memory_address = codec.read_uint8()

        # Invoke user implementation of remote function.
        _result = self._handler.readCurrent(slave_address, memory_address, memory_value)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IQSPIService.SERVICE_ID,
            request=interface.IQSPIService.READCURRENT_ID,
            sequence=sequence))
        if memory_value.value is None:
            raise ValueError("memory_value.value is None")
        codec.write_uint8(memory_value.value)
        codec.write_int32(_result)


